/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HospitalRouteImport } from './routes/hospital'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsNewRouteImport } from './routes/patients.new'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'
import { Route as ApiPublicConfigHospitalCodeRouteImport } from './routes/api/public/config.$hospitalCode'

const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoute = HospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PatientsRoute,
} as any)
const ApiPublicConfigHospitalCodeRoute =
  ApiPublicConfigHospitalCodeRouteImport.update({
    id: '/api/public/config/$hospitalCode',
    path: '/api/public/config/$hospitalCode',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/hospital': typeof HospitalRoute
  '/inventory': typeof InventoryRoute
  '/onboarding': typeof OnboardingRoute
  '/patients': typeof PatientsRouteWithChildren
  '/pharmacy': typeof PharmacyRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/api/public/config/$hospitalCode': typeof ApiPublicConfigHospitalCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/hospital': typeof HospitalRoute
  '/inventory': typeof InventoryRoute
  '/onboarding': typeof OnboardingRoute
  '/patients': typeof PatientsRouteWithChildren
  '/pharmacy': typeof PharmacyRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/api/public/config/$hospitalCode': typeof ApiPublicConfigHospitalCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/hospital': typeof HospitalRoute
  '/inventory': typeof InventoryRoute
  '/onboarding': typeof OnboardingRoute
  '/patients': typeof PatientsRouteWithChildren
  '/pharmacy': typeof PharmacyRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/api/public/config/$hospitalCode': typeof ApiPublicConfigHospitalCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/auth'
    | '/hospital'
    | '/inventory'
    | '/onboarding'
    | '/patients'
    | '/pharmacy'
    | '/patients/$id'
    | '/patients/new'
    | '/api/public/config/$hospitalCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/auth'
    | '/hospital'
    | '/inventory'
    | '/onboarding'
    | '/patients'
    | '/pharmacy'
    | '/patients/$id'
    | '/patients/new'
    | '/api/public/config/$hospitalCode'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/auth'
    | '/hospital'
    | '/inventory'
    | '/onboarding'
    | '/patients'
    | '/pharmacy'
    | '/patients/$id'
    | '/patients/new'
    | '/api/public/config/$hospitalCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  HospitalRoute: typeof HospitalRoute
  InventoryRoute: typeof InventoryRoute
  OnboardingRoute: typeof OnboardingRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  PharmacyRoute: typeof PharmacyRoute
  ApiPublicConfigHospitalCodeRoute: typeof ApiPublicConfigHospitalCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital': {
      id: '/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/api/public/config/$hospitalCode': {
      id: '/api/public/config/$hospitalCode'
      path: '/api/public/config/$hospitalCode'
      fullPath: '/api/public/config/$hospitalCode'
      preLoaderRoute: typeof ApiPublicConfigHospitalCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PatientsRouteChildren {
  PatientsIdRoute: typeof PatientsIdRoute
  PatientsNewRoute: typeof PatientsNewRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsIdRoute: PatientsIdRoute,
  PatientsNewRoute: PatientsNewRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  HospitalRoute: HospitalRoute,
  InventoryRoute: InventoryRoute,
  OnboardingRoute: OnboardingRoute,
  PatientsRoute: PatientsRouteWithChildren,
  PharmacyRoute: PharmacyRoute,
  ApiPublicConfigHospitalCodeRoute: ApiPublicConfigHospitalCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
